/* eslint-disable */
// Generated by GraphQL Code Generator. Run `npm run codegen` after schema changes.

export type Maybe<T> = T | null
export type TaskStatus = 'TODO' | 'IN_PROGRESS' | 'DONE'
export type TaskPriority = 'LOW' | 'MEDIUM' | 'HIGH'

export type DashboardQuery = {
  __typename?: 'Query'
  workspaces: Array<{
    __typename?: 'WorkspaceType'
    id: string
    name: string
    description?: Maybe<string>
    projects: Array<{
      __typename?: 'ProjectType'
      id: string
      name: string
      description?: Maybe<string>
      tasks: Array<{
        __typename?: 'TaskType'
        id: string
        title: string
        description?: Maybe<string>
        status: TaskStatus
        priority: TaskPriority
      }>
    }>
  }>
}

export type CreateWorkspaceMutation = {
  createWorkspace: { id: string; name: string; description?: Maybe<string> }
}
export type CreateWorkspaceMutationVariables = {
  input: { name: string; description?: Maybe<string> }
}

export type CreateProjectMutation = {
  createProject: { id: string; name: string; description?: Maybe<string> }
}
export type CreateProjectMutationVariables = {
  input: { workspaceId: string; name: string; description?: Maybe<string> }
}

export type CreateTaskMutation = {
  createTask: { id: string; title: string; status: TaskStatus; priority: TaskPriority }
}
export type CreateTaskMutationVariables = {
  input: {
    projectId: string
    title: string
    description?: Maybe<string>
    priority?: TaskPriority
  }
}

export type UpdateTaskStatusMutation = {
  updateTaskStatus: { id: string; status: TaskStatus }
}
export type UpdateTaskStatusMutationVariables = {
  input: { taskId: string; status: TaskStatus }
}
